#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf constant/fluid/polyMesh
rm -rf constant/solid/polyMesh

cleanCase

rm -rf 0

#------------------------------------------------------------------------------
