#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh -region fluid
mv log.blockMesh log.blockMesh.fluid
runApplication blockMesh -region solid
mv log.blockMesh log.blockMesh.solid

cp -r 0.org 0

runApplication setFields -region fluid

#-- Run on single processor
runApplication `getApplication`

#------------------------------------------------------------------------------
