#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

tar -xvf elbow.tar.gz

runApplication ideasUnvToFoam elbow.unv
runApplication polyDualMesh 30 -doNotPreserveFaceZones -concaveMultiCells -overwrite

for i in {1..3}
do
   rm log.refineWallLayer
   runApplication refineWallLayer "(wallLarge wallSmall)" 0.5 -overwrite
done

runApplication changeDictionary
runApplication transformPoints -scale "(0.001 0.001 0.001)"

cp -r 0.org 0

#runApplication potentialFoam

#runApplication $application



#------------------------------------------------------------------------------
