#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0 > /dev/null 2>&1
rm -rf *.obj
rm -rf constant/triSurface/*.stl constant/triSurface/*.eMesh
rm -rf constant/extendedFeatureEdgeMesh

cleanCase

#------------------------------------------------------------------------------
