#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# Decompose
runApplication decomposePar -allRegions

# Run in parallel
runParallel `getApplication`

# Reconstruct
runApplication reconstructPar -allRegions


#------------------------------------------------------------------------------
